name = "elorikids-nuxt"
main = ".output/server/index.mjs"
compatibility_date = "2025-07-15"
assets = { directory = ".output/public", binding = "ASSETS" }

workers_dev = false

[[d1_databases]]
binding = "DB"
database_name = "elorikids-db"
database_id = "6031f579-f2d6-42b1-a927-f420f2918550"
